language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 4
  - 6
  - 8
script:
  - 'npm run test:coverage'
after_success:
  - npm run semantic-release
  - 'bash <(curl -s https://codecov.io/bash)'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
