language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 4
  - 6
  - 7
script:
  - 'yarn run test:coverage'
after_success:
  - npm run semantic-release
  - 'bash <(curl -s https://codecov.io/bash)'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
